openapi: '3.0.2'
info:
  title: API Smart Home Web App
  version: '1.0'
servers:
  - url: http://192.168.1.17/smart-home/api/
    description: Odroid Server
  - url: http://localhost/smart-home/api/
    description: Development Server
paths: {}
components:
  schemas: {}