version: "3.8"
services:
  backend:
    image: smart-home-project/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  frontend:
    image: smart-home-project/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app

networks:
  default:
    external:
      name: agroupadvisor