version: "3.9"

services:
  backend:
    image: backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile.test
    ports:
      - '3000:3000'
    env_file:
      - ./app/backend/test.env
    environment:
      MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
  
  frontend:
    image: frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.test
    ports:
      - '8080:8080'
    volumes:
      - ./app/frontend:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    logging:
      driver: none

networks:
  default:
    external:
      name: smart-home-network