version: "3.9"

services:
  backend:
    image: backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./app/backend/dev.env
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
    volumes:
      - ./app/backend:/app

  frontend:
    image: frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./app/frontend:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    logging:
      driver: none

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH: ${MONGO_BASIC_AUTH}
    logging:
      driver: none

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Host port:Container port
    volumes:
      - ./app/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

networks:
  default:
    external:
      name: smart-home-network
