version: "3.9"

services:
  backend:
    image: backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./app/backend/.env
    environment:
      MONGODB_URL: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@smarthome.6upyefz.mongodb.net/?retryWrites=true&w=majority&appName=SmartHome
    volumes:
      - ./app/backend:/app
  
  frontend:
    image: frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./app/frontend:/app

networks:
  default:
    external:
      name: smart-home-network