version: "3.9"

services:
  backend:
    image: backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./app/backend/.env
    environment:
      MONGODB_URL: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@smarthome.6upyefz.mongodb.net/?retryWrites=true&w=majority&appName=SmartHome
    volumes:
      - ./app/backend:/app
  
  frontend:
    image: frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./app/frontend:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Host port:Container port
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

networks:
  default:
    external:
      name: smart-home-network