name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Docker Network
      run: docker network create smart-home-network

    - name: Build Images
      run: docker-compose -f docker-compose.test.yml build
      
    - name: Run Tests
      run: docker-compose -f docker-compose.test.yml up
